# Generated by Django 4.0.3 on 2022-03-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('slug', models.CharField(max_length=155, unique=True, verbose_name='url')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('slug', models.CharField(max_length=155, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Профессию',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('slug', models.CharField(max_length=155, unique=True, verbose_name='url')),
                ('age', models.PositiveSmallIntegerField(default=2022, verbose_name='Год выхода')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('run_time', models.CharField(help_text='Пример: 2 часа 15 минут', max_length=155, verbose_name='Длительность')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='app.celebrity', verbose_name='Актеры')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.celebrity', verbose_name='режиссер')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.genre', verbose_name='Жанр')),
                ('media', models.ManyToManyField(related_name='movies', to='app.media')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AddField(
            model_name='celebrity',
            name='filmography',
            field=models.ManyToManyField(related_name='celebrities', to='app.movie', verbose_name='Фильмы с его участием'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='media',
            field=models.ManyToManyField(related_name='celebrities', to='app.media'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celebrities', to='app.profession', verbose_name='Профессия'),
        ),
    ]
