# Generated by Django 4.0.3 on 2022-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='country',
            field=models.CharField(default='USA', max_length=155, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='date_of_birth',
            field=models.CharField(default='Введите дату', help_text='Пример: "22 Июня, 2022 года', max_length=155, verbose_name='Дата рождения'),
        ),
    ]
