# Generated by Django 4.0.3 on 2022-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_celebrity_biography_celebrity_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='https://youtube.com', help_text='Введите ссылку трейлера', verbose_name='Трейлер'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='biography',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='date_of_birth',
            field=models.CharField(help_text='Пример: "22 Июня, 2022 года', max_length=155, verbose_name='Дата рождения'),
        ),
    ]
