# Generated by Django 4.0.3 on 2022-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ratingstar_reviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age',
            new_name='year',
        ),
    ]
