# Generated by Django 4.0.3 on 2022-03-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_reviews_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ('-star',), 'verbose_name': 'Звезда(у)', 'verbose_name_plural': 'Звезды'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-created_at',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
